#include <discovery.idl>

module resources {	
	interface FrontTemperature : TransactionResource {
		double calculFrontTemperature(in double altitude , in double speed);
	};
	
	interface MediumTemperature : TransactionResource {
		double calculMediumTemperature(in double ft);
	};
	
	interface GlobalSensor : TransactionResource {
		double calculGlobalTempareature(in double mt);
	};
}